### PR TITLE
Fix Source links in static App

### LINKED ISSUE #619: Source File is missing from git Links in Header of static App
As of d473d6039c0190e98347d45dbda41f1dd80f5a5b. See [snapshot](https://snapshots.nextjournal.com/clerk/build/d473d6039c0190e98347d45dbda41f1dd80f5a5b/index.html#/CHANGELOG).

### PR DESCRIPTION
**Pull request by zampino**
Fix #619.

### CODE REVIEW

File: src/nextjournal/clerk/builder.clj [hunk 1]
```diff
@@ -293,11 +293,7 @@
                                                                             paths/*build-opts* opts
                                                                             viewer/doc-url (partial doc-url opts file)]
                                                                     (let [doc (eval/eval-analyzed-doc doc)]
-                                                                      (assoc doc :viewer (view/doc->viewer (assoc opts
-                                                                                                                  :nav-path (if (instance? java.net.URL file)
-                                                                                                                              (str "'" (:ns doc))
-                                                                                                                              (str file)))
-                                                                                                           doc))))
+                                                                      (assoc doc :viewer (view/doc->viewer (assoc opts :file-path (str file)) doc))))
```
Comment (zampino) [inline src/nextjournal/clerk/builder.clj:296]: I'm unsure whether I should keep also a `:nav-path`, but for a static app it is not used by the router nor by the viewer (e.g. in the header) I think.
