### PR TITLE
Error handling for missing tailwindcss executable

### LINKED ISSUE #507: document build! with :compile-css requiring tailwind executable
if you set the :compile-css option and don't have the tailwind executable, you get an error message that says the jvm failed to shell out, but doesn't tell you what command was missing.

### PR DESCRIPTION
**Pull request by mk**
Fixes #507.

### CODE REVIEW

**Comment by mk** [comment]
Added 89b5ac1158646363405fad03478e5f071b0b3197 because the error message is (imo) better. Before:
```
mk@mkair ~/d/clerk (fix-507) [1]> clj -X:nextjournal/clerk :paths '["notebooks/rule_30.clj"]' :compile-css true
[info] both `:paths` and `:paths-fn` are set, `:paths` will take precendence.
👷🏼 Clerk is building 1 notebooks…
🧐 Parsing… Done in 92.608ms. ✅
🔬 Analyzing… Done in 2002.903ms. ✅
🔨 Building "notebooks/rule_30.clj"… Done in 137.645ms. ✅
🎨 Compiling CSS… {:clojure.main/message
 "Execution error (IOException) at java.lang.ProcessImpl/forkAndExec (ProcessImpl.java:-2).\nerror=2, No such file or directory\n",
 :clojure.main/triage
 {:clojure.error/class java.io.IOException,
  :clojure.error/line -2,
  :clojure.error/cause "error=2, No such file or directory",
  :clojure.error/symbol java.lang.ProcessImpl/forkAndExec,
  :clojure.error/source "ProcessImpl.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.Exception,
    :message
    "Clerk could not find the `tailwindcss` executable. Please install it using `npm install -D tailwindcss` and try again.",
    :at
    [nextjournal.clerk.builder$compile_css_BANG_$fn__17347
     invoke
     "builder.clj"
     317]}
   {:type java.io.IOException,
    :message
    "Cannot run program \"tailwindcsss\": error=2, No such file or directory",
    :at [java.lang.ProcessBuilder start "ProcessBuilder.java" 1143]}
   {:type java.io.IOException,
    :message "error=2, No such file or directory",
    :at [java.lang.ProcessImpl forkAndExec "ProcessImpl.java" -2]}],
  :trace
  [[java.lang.ProcessImpl forkAndExec "ProcessImpl.java" -2]
   [java.lang.ProcessImpl <init> "ProcessImpl.java" 319]
   [java.lang.ProcessImpl start "ProcessImpl.java" 249]
   [java.lang.ProcessBuilder start "ProcessBuilder.java" 1110]
   [java.lang.ProcessBuilder start "ProcessBuilder.java" 1073]
   [babashka.process$process_STAR_ invokeStatic "process.cljc" 357]
   [babashka.process$process_STAR_ invoke "process.cljc" 329]
   [babashka.process$sh invokeStatic "process.cljc" 554]
   [babashka.process$sh doInvoke "process.cljc" 544]
   [clojure.lang.RestFn invoke "RestFn.java" 619]
   [nextjournal.clerk.builder$compile_css_BANG_$fn__17347
    invoke
    "builder.clj"
    317]
   [nextjournal.clerk.builder$compile_css_BANG_
    invokeStatic
    "builder.clj"
    317]
   [nextjournal.clerk.builder$compile_css_BANG_
    invoke
    "builder.clj"
    298]
   [nextjournal.clerk.builder$build_static_app_BANG_
    invokeStatic
    "builder.clj"
    414]
   [nextjournal.clerk.builder$build_static_app_BANG_
    invoke
    "builder.clj"
    369]
   [nextjournal.clerk$build_BANG_ invokeStatic "clerk.clj" 509]
   [nextjournal.clerk$build_BANG_ invoke "clerk.clj" 467]
   [clojure.lang.Var invoke "Var.java" 384]
   [clojure.run.exec$exec invokeStatic "exec.clj" 89]
   [clojure.run.exec$exec invoke "exec.clj" 78]
   [clojure.run.exec$_main$fn__219 invoke "exec.clj" 216]
   [clojure.run.exec$_main invokeStatic "exec.clj" 212]
   [clojure.run.exec$_main doInvoke "exec.clj" 180]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "error=2, No such file or directory"}}

Execution error (IOException) at java.lang.ProcessImpl/forkAndExec (ProcessImpl.java:-2).
error=2, No such file or directory
```

after
```
mk@mkair ~/d/clerk (fix-507) [1]> clj -X:nextjournal/clerk :paths '["notebooks/rule_30.clj"]' :compile-css true
[info] both `:paths` and `:paths-fn` are set, `:paths` will take precendence.
👷🏼 Clerk is building 1 notebooks…
🧐 Parsing… Done in 117.607ms. ✅
🔬 Analyzing… Done in 1967.063ms. ✅
🔨 Building "notebooks/rule_30.clj"… Done in 130.027ms. ✅
🎨 Compiling CSS… {:clojure.main/message
 "Execution error at nextjournal.clerk.builder/compile-css!$fn (builder.clj:317).\nClerk could not find the `tailwindcss` executable. Please install it using `npm install -D tailwindcss` and try again.\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.Exception,
  :clojure.error/line 317,
  :clojure.error/cause
  "Clerk could not find the `tailwindcss` executable. Please install it using `npm install -D tailwindcss` and try again.",
  :clojure.error/symbol nextjournal.clerk.builder/compile-css!$fn,
  :clojure.error/source "builder.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.Exception,
    :message
    "Clerk could not find the `tailwindcss` executable. Please install it using `npm install -D tailwindcss` and try again.",
    :at
    [nextjournal.clerk.builder$compile_css_BANG_$fn__17347
     invoke
     "builder.clj"
     317]}],
  :trace
  [[nextjournal.clerk.builder$compile_css_BANG_$fn__17347
    invoke
    "builder.clj"
    317]
   [nextjournal.clerk.builder$compile_css_BANG_
    invokeStatic
    "builder.clj"
    317]
   [nextjournal.clerk.builder$compile_css_BANG_
    invoke
    "builder.clj"
    298]
   [nextjournal.clerk.builder$build_static_app_BANG_
    invokeStatic
    "builder.clj"
    414]
   [nextjournal.clerk.builder$build_static_app_BANG_
    invoke
    "builder.clj"
    369]
   [nextjournal.clerk$build_BANG_ invokeStatic "clerk.clj" 509]
   [nextjournal.clerk$build_BANG_ invoke "clerk.clj" 467]
   [clojure.lang.Var invoke "Var.java" 384]
   [clojure.run.exec$exec invokeStatic "exec.clj" 89]
   [clojure.run.exec$exec invoke "exec.clj" 78]
   [clojure.run.exec$_main$fn__219 invoke "exec.clj" 216]
   [clojure.run.exec$_main invokeStatic "exec.clj" 212]
   [clojure.run.exec$_main doInvoke "exec.clj" 180]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Clerk could not find the `tailwindcss` executable. Please install it using `npm install -D tailwindcss` and try again."}}

Execution error at nextjournal.clerk.builder/compile-css!$fn (builder.clj:317).
Clerk could not find the `tailwindcss` executable. Please install it using `npm install -D tailwindcss` and try again.
```

Or do folks have a better idea? cc @hiredman.

File: src/nextjournal/clerk/builder.clj [hunk 1]
```diff
@@ -314,14 +314,16 @@
...
+          (try (sh "tailwindcss"
+                   "--input"  tw-input
+                   "--config" tw-config
+                   ;; FIXME: pass inline
+                   ;;"--content" (str tw-viewer)
+                   ;;"--content" (str tw-folder "/**/*.edn")
+                   "--output" tw-output
+                   "--minify")
+               (catch java.io.IOException _
+                 (throw (Exception. "Clerk could not find the `tailwindcss` executable. Please install it using `npm install -D tailwindcss` and try again."))))]
```
Comment (mk) [inline src/nextjournal/clerk/builder.clj:326]: The install hint in the error is actually not correct which is why I didn't merge it. We currently only rely on the standalone `tailwindcss` executable, so installing it via `npm install -D tailwindcss` won't work (we'd need to call it via npx then). Do we want to support both installation methods?

Comment (zampino) [reply src/nextjournal/clerk/builder.clj:326]: I see, maybe relying on the standalone executable was a mistake (see also https://github.com/nextjournal/clerk/blob/d80187013d7b7b96db3d8b114b8d99f687170668/.github/workflows/main.yml#L201-L200). 

Maybe we could probe the exit code of `npx tailwindcss` and then fallback to `tailwindcss` for legacy projects?

Actually we need `npm install -D tailwindcss @tailwindcss/typography` with our config.
