### PR TITLE
Metadata handling fixes in analyzer for #488 and #489

### LINKED ISSUE #488: Analyzer sensitive to unknown class tags in forms
The analyzer will die on code that clojure runs just fine.  If I define a method which uses type tag metadata and the class is not known, it will compile and run fine, but clerk will error out when analyzing. 

Here is a minimal example that triggers it:

```clojure
(require '[nextjournal.clerk :as clerk])

;; this is a brute way to make the clerk analyzer resilient in the case of
;; an unknown class tag
;;
;; (alter-var-root #'nextjournal.clerk.analyzer/analyzer-passes-opts
;;                 (fn [v]
;;                   (assoc v
;;                          :validate/wrong-tag-handler (fn [tag node]
;;                                                        nil))))

;; This will compile and run just fine, but clerk errors when evaluating this as
;; a notebook.
(defmulti foo :tag)
(defmethod foo :baz [v] (pr ^Something v))
(foo {:tag :baz})
```

I think that ignoring those unresolvable tags is fine, but I am still learning clerk internals.

### PR DESCRIPTION
**Pull request by craig-latacora**
This PR fixes the issues mentioned, by stripping metadata from forms before printing them to hash, and by not throwing an exception on an unrecognized class in a :type metadata tag.

closes #488 and #489

### CODE REVIEW

File: src/nextjournal/clerk/analyzer.clj [hunk 1]
```diff
@@ -544,12 +549,21 @@
 #_(dep/immediate-dependencies (:graph (build-graph "src/nextjournal/clerk/analyzer.clj"))  #'nextjournal.clerk.analyzer/long-thing)
 #_(dep/transitive-dependencies (:graph (build-graph "src/nextjournal/clerk/analyzer.clj"))  #'nextjournal.clerk.analyzer/long-thing)
 
+(defn strip-form-meta [form]
+  (clojure.walk/postwalk
+   (fn [v]
+     (if (or (instance? clojure.lang.IObj v)
+             (instance? clojure.lang.IMeta v))
```
Comment (zampino) [inline src/nextjournal/clerk/analyzer.clj:556]: Hi @craig-latacora thank you for your pr!

If I can see correctly, a more correct check would be just `(instance? clojure.lang.IObj v)`. While it's unlikely that this `form` contains complex non-literal values, strictly looking at the interface definitions an object needs to implement `IObj` to be called `vary-meta` upon. For instance a var is IMeta but not IObj.

Comment (zampino) [reply src/nextjournal/clerk/analyzer.clj:556]: I've pushed your changes + some cleanup internally to https://github.com/nextjournal/clerk/compare/latacora/strip-meta?expand=1.
