### PR TITLE
Fix analyzer issues with clojure proxy

### LINKED ISSUE #222: Analysis error for ns with `proxy` expression
The following doc

```clojure
(ns proxy-test)
(proxy [clojure.lang.ISeq][])
```

Will produce an exception:
```
1. Unhandled clojure.lang.ExceptionInfo
   Could not resolve var:
   proxy_test.proxy$java.lang.Object$ISeq$e982161
   {:var proxy-test/proxy_test.proxy$java.lang.Object$ISeq$e982161,
    :form (proxy [clojure.lang.ISeq] [])}
              analyzer.clj:  258  nextjournal.clerk.analyzer/analyze-doc/fn
                Range.java:  180  clojure.lang.Range/reduce
                  core.clj: 6829  clojure.core/reduce
                  core.clj: 6812  clojure.core/reduce
              analyzer.clj:  231  nextjournal.clerk.analyzer/analyze-doc
              analyzer.clj:  226  nextjournal.clerk.analyzer/analyze-doc
              analyzer.clj:  228  nextjournal.clerk.analyzer/analyze-doc
              analyzer.clj:  226  nextjournal.clerk.analyzer/analyze-doc
                      REPL:  269  nextjournal.clerk.analyzer/eval71596
                      REPL:  269  nextjournal.clerk.analyzer/eval71596
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  218  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  217  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  833  java.lang.Thread/run
```

This is a fault in Clerk's detection of when a var that exists at runtime but was removed from the file.

### PR DESCRIPTION
**Pull request by zampino**
Fixes a regression in analyzer introduced with 01875b21be921b8ca91611d9d06f0142a7a1e157  which prevents notebooks with calls to `clojure.core/proxy` to be evaluated.

Fixes #222.

### CODE REVIEW

File: src/nextjournal/clerk/analyzer.clj [hunk 1]
```diff
@@ -243,14 +248,14 @@
                                          (and doc? (not (contains? state :ns))) (merge (parser/->doc-settings form) {:ns *ns*}))]
                              (when-let [missing-dep (and (:ns? state)
                                                          (first (set/difference (into #{}
-                                                                                      (filter #(and (symbol? %)
-                                                                                                    (#{(-> state :ns ns-name name)} (namespace %))))
+                                                                                      (comp (filter #(and (symbol? %)
+                                                                                                     (#{(-> state :ns ns-name name)} (namespace %))))
+                                                                                            (remove clojure-internal?))
```
Comment (zampino) [inline src/nextjournal/clerk/analyzer.clj:253]: I felt more at ease with a fix, specific for the proxy case. Instead of any names with a dollar inside. Following the pattern of [`proxy-name`](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core_proxy.clj#L37-L46). We can add to the predicate if we encounter more cases like this.

File: src/nextjournal/clerk/analyzer.clj [hunk 2]
```diff
@@ -217,6 +218,21 @@
   (-> (reduce add-block-id (assoc analyzed-doc :blocks [] :id->count {} ) blocks)
       (dissoc :id->count)))
 
+(defn ^:private internal-proxy-name?
+  "Returns true if `sym` represents a var name interned by `clojure.core/proxy`."
+  [sym]
+  (str/includes? (name sym) ".proxy$"))
```
Comment (mk) [inline src/nextjournal/clerk/analyzer.clj:224]: I think it's better to make this a `defn` so the arg becomes apparent. Also I've changed the name to be more narrow in order to match the implementation. We can change the implementation when we grow it.

File: src/nextjournal/clerk/analyzer.clj [hunk 3]
```diff
@@ -217,6 +218,21 @@
...
+
+(defn throw-if-dep-is-missing [doc state analyzed]
+  (when-let [missing-dep (and (first (set/difference (into #{}
+                                                           (comp (filter #(and (symbol? %)
+                                                                               (#{(-> state :ns ns-name name)} (namespace %))))
+                                                                 (remove internal-proxy-name?))
+                                                           (:deps analyzed))
+                                                     (-> state :->analysis-info keys set))))]
+    (throw (ex-info (str "The var `#'" missing-dep "` exists at runtime, but Clerk cannot find it in the namespace. Did you remove it?")
+                    (merge {:var-name missing-dep} (select-keys analyzed [:form]) (select-keys doc [:file]))))))
```
Comment (mk) [inline src/nextjournal/clerk/analyzer.clj:234]: This is my attempt to integrate the takeaways from https://www.thestrangeloop.com/2022/expert-software-developers-approach-to-error.html into Clerk's development. When I first encountered the error, I didn't even notice it's coming from Clerk (otherwise I would have been able to fix it immediately).

I also experimented with going more into the rationale of this feature and letting folks know why this exists but I feel like this is better explained in longer form elsewhere. Was thinking to include a link at first but it would be even better if Clerk just showed an error where folks can opt into a rich view with more information.
